= Parameters

The parent key for all of the following parameters is `stackgres_operator`.

== `namespace`

[horizontal]
type:: string
default:: `syn-stackgres-operator`

The namespace in which to deploy this component.

== `helmValues`

[horizontal]
type:: dict

List of Helm values to pass to the Helm chart.
For a list of supported values see: https://stackgres.io/doc/latest/install/operator/parameters/[stackgres operator parameters].


By default, the rest API is disabled and certificate management by cert-manager is enabled.

[WARNING]
====
This means by default this component requires a working cert-manager instance on the cluster.
If cert-manager isn't installed on the target cluster, disable cert-manager support by setting `helmValues.cert.certManager.autoConfigure: false`.
====

[IMPORTANT]
====
If you need to switch from or the cert-manager generated certificates you will have to manually remove the secrets `stackgres-operator-certs` and `stackgres-operator-ca` *before* applying the catalog.
====

== Example

[source,yaml]
----
namespace: my-stackgres-operator
helmValues:
  deploy:
    restapi: true
  adminui:
    service:
      type: LoadBalancer
----
